version: '3.7'
services:
  food_delivery_restapi:
    container_name: food_delivery_restapi
    image: "postgres"
    env_file:
      - ./config/.dev.env
    volumes:
      - ./pg_data:/var/lib/postgresql/data/ 
    ports:
      - 5432:5432
